### ISSUE TITLE
Incompatibility on Minecraft 1.19 with Quilt

### ISSUE THREAD

**Issue by lhvy** [zatrit/openmcskins#1]
When using OpenMCSkins on the latest version of Minecraft + Quilt (as of 26/06/2022), the game refuses crashes, and Quilt Loader gives the following error:

```
Uncaught exception in thread "main":
Runtime Exception: Mixin transformation of org.quiltmc.loader.impl.launch.knot.UnusedEmptyTargetClass failed
  NoClassDefFoundError: net/fabricmc/loader/util/version/SemanticVersionPredicateParser
    ClassNotFound Exception: net.fabricmc.loader.util.version.SemanticVersionPredicateParser
```

I was still able to reproduce this after cutting my mods down to just: OpenMCSkins, Cloth Config API, Mod Menu, Quilted Fabric API/Quilt Standard Libraries. All the latest versions for Fabric/Quilt with Minecraft 1.19, downloaded today.

OpenMCSkins is listed as compatible with Quilt on Modrinth, am I doing something wrong or missing a dependency?

**Comment by Southpaw1496** [comment]
It is incompatible because it is using Fabric Loader Internals, which Quilt does not support. Though I'm not a developer myself I don't think you're really meant to be using them.

**Comment by zatrit** [comment]
I'll fix it when I get home in about 3 weeks as I'm on vacation right now
