### ISSUE TITLE
incompatibility with [fabric]capes mod + suggestion

### ISSUE THREAD

**Issue by Mafy-17** [zatrit/openmcskins#10]
Fabric capes mod is not compatible with openmcskin mod sadly so if you could make it compatible it would be amazing thanks :)  and It would be nice of you could somehow include essential mod stuff to be visible as well with this mod

**Comment by zatrit** [comment]
The FabricCapes mod implements the same functionality as OpenMCSkins, so they just breaks each other.
Essentials doesn't provide a public API, or at least I haven't found one
