### ISSUE TITLE
Cloak+ doesn't work on player (me) 

### ISSUE THREAD

**Issue by poopman97** [zatrit/openmcskins#4]
Cloaks+ works on other players that have it but on me It doesn't even though it's enabled

I have all of the mods installed 
Minecraft version 1.19.2
Cosmetica cosmetics work without any problems
Config
```
animatedCapes: true
cosmetics: true
ears: true
forceIcons: true
fullErrorMessage: false
hashingAlgorithm: MURMUR3
hosts:
- !cosmetica ''
- !labymod ''
- !fivezig ''
- !mantle ''
- !tlauncher ''
- !optifine ''
- !elyby ''
- !mojang ''
resolvingTimeout: 10
uuidResolutionMod
```

**Comment by zatrit** [comment]
Did you tried to add ```- !cloaksplus ''``` to hosts?

**Comment by poopman97** [comment]
Thanks it works, also it would be nice if that would be added to the wiki
