### ISSUE TITLE
Incompatibility with "'Slight' GUI Modifications" mod

### ISSUE THREAD

**Issue by brucethemoose** [zatrit/openmcskins#5]
Crash with OpenMCSkins and that mod (and only required dependencies) enabled:  https://mclo.gs/zSMPyqK

Same instance with "'Slight' GUI Modifications" disabled: https://mclo.gs/qzoov86

On a separate note... is 1.19.2 supported?

**Comment by brucethemoose** [comment]
@shedaniel You may be interested in this as well.

**Comment by zatrit** [comment]
Looks like OpenMCSkins is trying to find Fabric-ASM but can't find it.  I don't have access to my PC right now, but I'll fix it soon

**Comment by zatrit** [comment]
I fixed this
