### ISSUE TITLE
Doesn't work with Optifabric

### ISSUE THREAD

**Issue by DarkStarOnGitHub** [zatrit/openmcskins#7]
It causes this issue whenever I use the mod with Optifabric. Could you make it compatible?
openmcskins version: 1.3.7 (even though I put 1.3.8 version, it shows 1.3.7)
optifabric version: 1.13.6
optifine version: Optifine HD U H9
![image_2022-09-24_121155669](https://user-images.githubusercontent.com/113664296/192083893-5b5f7b35-796a-4a2c-8418-50575289169b.png)

**Comment by DarkStarOnGitHub** [comment]
![image_2022-09-24_121347369](https://user-images.githubusercontent.com/113664296/192083948-5fd032da-ee5f-4341-8db9-62e0b071b8a7.png)

Console screenshot

**Comment by zatrit** [comment]
Optifine breaks OpenMCSkins, and therefore I indicated the incompatibility in the fabric.mod.json file

**Comment by DarkStarOnGitHub** [comment]
Ok 👍
