### ISSUE TITLE
Add support for Valhalla Skin Server

### ISSUE THREAD

**Issue by MimzyFang** [zatrit/openmcskins#8]
Not really high priority since they have their own mod, but It would be cool for seeing skins from more skin servers 

wiki for the API https://github.com/killjoy1221/ValhallaSkinServer/wiki/Endpoints

**Comment by zatrit** [comment]
In other issues I wrote that I was trying to rewrite this mod from scratch. If I succeed, I'll add Valhalla Skins support to the new, more stable version

**Comment by MimzyFang** [comment]
Please note that the wiki I linked to has since become outdated [here](https://skins.minelittlepony-mod.com/docs) are the new docs

**Comment by zatrit** [comment]
Added in OpenMCSkins 2.0.4 (but it's only early build, published on the discord server)

**Comment by zatrit** [comment]
First alpha version was published on Modrinth with Valhalla support
